services:
  backend:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
    environment:
      - PGURL=postgresql://postgres:postgres@db:5432/le-grand
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    build:
      context: api/services/db/sqlmodel
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: le-grand
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
